require 'report_builder'

ReportBuilder.configure do |config|
  config.input_path = 'reports/cucumber_report.json' # JSON file generated by Cucumber
  config.report_path = 'reports/cucumber_html_report' # Output report file
  config.report_types = [:html] # Can be :html, :json, :retry, :report or an array of these
  config.report_title = 'Test Report' # Report title
  config.compress_images = false # If images should be compressed
  config.additional_info = {browser: 'Chrome', environment: 'Test'} # Add custom info
end

ReportBuilder.build_report
