version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:3.2-node-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Run Cucumber Tests
          command: bundle exec cucumber

workflows:
  version: 2
  test_workflow:
    jobs:
      - test