version: 2.1

executors:
  ruby-executor:
    docker:
      - image: circleci/ruby:3.3.4
        environment:
          BUNDLE_PATH: vendor/bundle
          DISPLAY: ":99.0"

jobs:
  setup:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            gem install bundler
            bundle install

  test:
    executor: ruby-executor
    steps:
      - checkout
      - run:
          name: Start Xvfb
          command: Xvfb :99 -screen 0 1280x1024x24 &
      - run:
          name: Run Cucumber Tests
          command: bundle exec cucumber --format pretty --backtrace

workflows:
  version: 2
  test-workflow:
    jobs:
      - setup
      - test:
          requires:
            - setup
