name: Ruby CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Adjust based on your version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: List Files for Debugging
        run: |
          ls -R features/pages

      - name: Run Tests
        run: bundle exec cucumber features/hyperfiber.feature
