name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    #services:
      # Optional: Set up services like databases if needed
      # db:
      #   image: mysql:5.7
      #   ports: ['3306:3306']
      #   options: >-
      #     --health-cmd="mysqladmin ping"
      #     --health-interval=10s
      #     --health-timeout=5s
      #     --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'  # Specify the Ruby version you are using
        bundler-cache: true  # Caches gems to speed up subsequent runs

    - name: Install dependencies
      run: |
        bundle install

    - name: Run Cucumber Tests
      run: |
        bundle exec cucumber
      env:
        DISPLAY: ":99.0"  # Required for headless browser testing
